In [1]:
import pandas as pd

In [2]:
a = pd.read_csv('FoodBalanceSheets_E_Africa_NOFLAG.csv',encoding='latin-1')

In [3]:
#11a
a.groupby('Item')['Y2014'].sum()

Item
Alcohol, Non-Food        2403.00
Alcoholic Beverages    102410.11
Animal Products         11935.65
Animal fats            209460.54
Apples and products      9499.23
                         ...
Vegetables, Other      155038.96
Vegetal Products       107145.19
Wheat and products     232670.13
Wine                     4497.36
Yams                   200396.96
Name: Y2014, Length: 119, dtype: float64

In [4]:
#11b
a.groupby('Item')['Y2017'].sum()

Item
Alcohol, Non-Food        2348.00
Alcoholic Beverages     95581.06
Animal Products         11547.65
Animal fats            269617.53
Apples and products     10198.90
                         ...
Vegetables, Other      157752.59
Vegetal Products       107655.20
Wheat and products     240047.62
Wine                     4178.02
Yams                   229174.59
Name: Y2017, Length: 119, dtype: float64

In [5]:
#12, mean and sd for 2015
a.describe()

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
count,60943.000000,60943.000000,60943.000000,59354.000000,59395.000000,59408.000000,59437.000000,59507.000000
mean,134.265576,2687.176706,3814.856456,134.196282,135.235966,136.555222,140.917765,143.758381
std,72.605709,146.055739,2212.007033,1567.663696,1603.403984,1640.007194,1671.862359,1710.782658
min,4.000000,2501.000000,511.000000,-1796.000000,-3161.000000,-3225.000000,-1582.000000,-3396.000000
25%,74.000000,2562.000000,684.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,136.000000,2630.000000,5142.000000,0.090000,0.080000,0.080000,0.100000,0.070000
75%,195.000000,2775.000000,5511.000000,8.340000,8.460000,8.430000,9.000000,9.000000
max,276.000000,2961.000000,5911.000000,176405.000000,181137.000000,185960.000000,190873.000000,195875.000000

In [6]:
#13, total number of missing data in 2016
a.isnull().sum()

Area Code          0
Area               0
Item Code          0
Item               0
Element Code       0
Element            0
Unit               0
Y2014           1589
Y2015           1548
Y2016           1535
Y2017           1506
Y2018           1436
dtype: int64

In [7]:
#14a
a.groupby('Element Code').sum()

,Area Code,Item Code,Y2014,Y2015,Y2016,Y2017,Y2018
Element Code,,,,,,,
511,6020,112545,1031585.00,1058081.00,1085107.00,1112641.00,1140605.00
645,658446,13185401,49650.63,49345.13,48985.28,48690.04,49056.85
664,674057,13511060,454257.00,453383.00,451810.00,454681.00,455261.00
674,675050,13535000,11836.46,11833.95,11779.69,11842.45,11833.56
684,675050,13535000,10225.56,10235.74,10102.77,10253.84,10258.69
5072,571566,11329527,58749.83,34910.99,33140.12,54316.91,20577.91
5123,274353,5424803,153223.00,155439.00,157787.00,160614.00,163902.00
5131,271940,5350416,282923.00,287929.00,280631.00,292836.00,308429.00
5142,663295,13285035,1212332.49,1232361.10,1247022.17,1258888.28,1303841.28
5154,235554,4729749,78718.13,66254.41,69563.68,91645.97,91300.97
5170,623271,12421089,30149.00,30045.00,37224.00,35500.00,34864.00
5171,50308,1486528,416.00,349.00,89.00,91.00,90.00
5301,708993,14197445,1996716.35,2021493.55,2044842.70,2088198.10,2161192.10
5511,526751,10450053,1931287.75,1947019.39,1943537.15,2030056.89,2075072.89
5521,176272,3538507,216927.89,225050.22,228958.65,223705.68,233489.68
5527,103537,2035933,21922.92,23976.82,23389.20,24870.14,25263.14
5611,688174,13795966,274144.48,267018.46,286582.78,294559.09,287997.09
5911,599910,11840553,150020.64,157614.47,151920.46,182338.80,181594.80

In [8]:
#14b
b = a.groupby('Element Code').sum()

In [9]:
#14c
b.mode()

,Area Code,Item Code,Y2014,Y2015,Y2016,Y2017,Y2018
0,675050.0,13535000.0,416.00,349.00,89.00,91.00,90.00
1,NaN,NaN,10225.56,10235.74,10102.77,10253.84,10258.69
2,NaN,NaN,11836.46,11833.95,11779.69,11842.45,11833.56
3,NaN,NaN,21922.92,23976.82,23389.20,24870.14,20577.91
4,NaN,NaN,30149.00,30045.00,33140.12,35500.00,25263.14
5,NaN,NaN,49650.63,34910.99,37224.00,48690.04,34864.00
6,NaN,NaN,58749.83,49345.13,48985.28,54316.91,49056.85
7,NaN,NaN,78718.13,66254.41,69563.68,91645.97,91300.97
8,NaN,NaN,150020.64,155439.00,151920.46,160614.00,163902.00
9,NaN,NaN,153223.00,157614.47,157787.00,182338.80,181594.80
10,NaN,NaN,216927.89,225050.22,228958.65,223705.68,233489.68
11,NaN,NaN,274144.48,267018.46,280631.00,292836.00,287997.09
12,NaN,NaN,282923.00,287929.00,286582.78,294559.09,308429.00
13,NaN,NaN,454257.00,453383.00,451810.00,454681.00,455261.00
14,NaN,NaN,1031585.00,1058081.00,1085107.00,1112641.00,1140605.00
15,NaN,NaN,1212332.49,1232361.10,1247022.17,1258888.28,1303841.28
16,NaN,NaN,1931287.75,1947019.39,1943537.15,2030056.89,2075072.89
17,NaN,NaN,1996716.35,2021493.55,2044842.70,2088198.10,2161192.10

In [10]:
#15
a.groupby('Element').sum()

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
Element,,,,,,,,
Domestic supply quantity,708993,14197445,28068795,1996716.35,2021493.55,2044842.70,2088198.10,2161192.10
Export Quantity,599910,11840553,26026133,150020.64,157614.47,151920.46,182338.80,181594.80
Fat supply quantity (g/capita/day),675050,13535000,3435732,10225.56,10235.74,10102.77,10253.84,10258.69
Feed,176272,3538507,7282199,216927.89,225050.22,228958.65,223705.68,233489.68
Food,663295,13285035,25406622,1212332.49,1232361.10,1247022.17,1258888.28,1303841.28
Food supply (kcal/capita/day),674057,13511060,3329296,454257.00,453383.00,451810.00,454681.00,455261.00
Food supply quantity (kg/capita/yr),658446,13185401,3163725,49650.63,49345.13,48985.28,48690.04,49056.85
Import Quantity,688174,13795966,28834929,274144.48,267018.46,286582.78,294559.09,287997.09
Losses,274353,5424803,10292107,153223.00,155439.00,157787.00,160614.00,163902.00
Other uses (non-food),235554,4729749,8926728,78718.13,66254.41,69563.68,91645.97,91300.97
Processing,271940,5350416,10313310,282923.00,287929.00,280631.00,292836.00,308429.00
Production,526751,10450053,21388191,1931287.75,1947019.39,1943537.15,2030056.89,2075072.89
Protein supply quantity (g/capita/day),675050,13535000,3385502,11836.46,11833.95,11779.69,11842.45,11833.56
Residuals,623271,12421089,24066350,30149.00,30045.00,37224.00,35500.00,34864.00
Seed,103537,2035933,4211574,21922.92,23976.82,23389.20,24870.14,25263.14
Stock Variation,571566,11329527,21464704,58749.83,34910.99,33140.12,54316.91,20577.91
Total Population - Both sexes,6020,112545,22995,1031585.00,1058081.00,1085107.00,1112641.00,1140605.00
Tourist consumption,50308,1486528,2869905,416.00,349.00,89.00,91.00,90.00

In [11]:
#16
a.groupby('Element')['Y2014'].sum()

Element
Domestic supply quantity                  1996716.35
Export Quantity                            150020.64
Fat supply quantity (g/capita/day)          10225.56
Feed                                       216927.89
Food                                      1212332.49
Food supply (kcal/capita/day)              454257.00
Food supply quantity (kg/capita/yr)         49650.63
Import Quantity                            274144.48
Losses                                     153223.00
Other uses (non-food)                       78718.13
Processing                                 282923.00
Production                                1931287.75
Protein supply quantity (g/capita/day)      11836.46
Residuals                                   30149.00
Seed                                        21922.92
Stock Variation                             58749.83
Total Population - Both sexes             1031585.00
Tourist consumption                           416.00
Name: Y2014, dtype: float64

In [12]:
#17
a.groupby('Element')['Y2018'].sum()

Element
Domestic supply quantity                  2161192.10
Export Quantity                            181594.80
Fat supply quantity (g/capita/day)          10258.69
Feed                                       233489.68
Food                                      1303841.28
Food supply (kcal/capita/day)              455261.00
Food supply quantity (kg/capita/yr)         49056.85
Import Quantity                            287997.09
Losses                                     163902.00
Other uses (non-food)                       91300.97
Processing                                 308429.00
Production                                2075072.89
Protein supply quantity (g/capita/day)      11833.56
Residuals                                   34864.00
Seed                                        25263.14
Stock Variation                             20577.91
Total Population - Both sexes             1140605.00
Tourist consumption                            90.00
Name: Y2018, dtype: float64

In [13]:
highest_sum_in_2018 = a.groupby('Element')['Y2018'].sum()

In [14]:
highest_sum_in_2018.mode() #Domestic supply quantity

0          90.00
1       10258.69
2       11833.56
3       20577.91
4       25263.14
5       34864.00
6       49056.85
7       91300.97
8      163902.00
9      181594.80
10     233489.68
11     287997.09
12     308429.00
13     455261.00
14    1140605.00
15    1303841.28
16    2075072.89
17    2161192.10
Name: Y2018, dtype: float64

In [15]:
#18
a.groupby('Element')['Y2018'].sum()

Element
Domestic supply quantity                  2161192.10
Export Quantity                            181594.80
Fat supply quantity (g/capita/day)          10258.69
Feed                                       233489.68
Food                                      1303841.28
Food supply (kcal/capita/day)              455261.00
Food supply quantity (kg/capita/yr)         49056.85
Import Quantity                            287997.09
Losses                                     163902.00
Other uses (non-food)                       91300.97
Processing                                 308429.00
Production                                2075072.89
Protein supply quantity (g/capita/day)      11833.56
Residuals                                   34864.00
Seed                                        25263.14
Stock Variation                             20577.91
Total Population - Both sexes             1140605.00
Tourist consumption                            90.00
Name: Y2018, dtype: float64

In [16]:
#3rd_lowest_sum from Output 14 -- Protein supply quantity

In [17]:
#19
a.groupby('Area')['Element'].sum()

Area
Algeria                        Total Population - Both sexesDomestic supply q...
Angola                         Total Population - Both sexesDomestic supply q...
Benin                          Total Population - Both sexesDomestic supply q...
Botswana                       Total Population - Both sexesDomestic supply q...
Burkina Faso                   Total Population - Both sexesDomestic supply q...
Cabo Verde                     Total Population - Both sexesDomestic supply q...
Cameroon                       Total Population - Both sexesDomestic supply q...
Central African Republic       Total Population - Both sexesDomestic supply q...
Chad                           Total Population - Both sexesDomestic supply q...
Comoros                        Import QuantityDomestic supply quantityOther u...
Congo                          Total Population - Both sexesDomestic supply q...
Côte d'Ivoire                  Total Population - Both sexesDomestic supply q...
Djibouti                       Total Population - Both sexesDomestic supply q...
Egypt                          Total Population - Both sexesDomestic supply q...
Eswatini                       Total Population - Both sexesDomestic supply q...
Ethiopia                       Total Population - Both sexesDomestic supply q...
Ethiopia PDR                   Import QuantityDomestic supply quantityOther u...
Gabon                          Total Population - Both sexesDomestic supply q...
Gambia                         Total Population - Both sexesDomestic supply q...
Ghana                          Total Population - Both sexesDomestic supply q...
Guinea                         Total Population - Both sexesDomestic supply q...
Guinea-Bissau                  Total Population - Both sexesDomestic supply q...
Kenya                          Total Population - Both sexesDomestic supply q...
Lesotho                        Total Population - Both sexesDomestic supply q...
Liberia                        Total Population - Both sexesDomestic supply q...
Madagascar                     Total Population - Both sexesDomestic supply q...
Malawi                         Total Population - Both sexesDomestic supply q...
Mali                           Total Population - Both sexesDomestic supply q...
Mauritania                     Total Population - Both sexesDomestic supply q...
Mauritius                      Total Population - Both sexesDomestic supply q...
Morocco                        Total Population - Both sexesDomestic supply q...
Mozambique                     Total Population - Both sexesDomestic supply q...
Namibia                        Total Population - Both sexesDomestic supply q...
Niger                          Total Population - Both sexesDomestic supply q...
Nigeria                        Total Population - Both sexesDomestic supply q...
Rwanda                         Total Population - Both sexesDomestic supply q...
Sao Tome and Principe          Total Population - Both sexesDomestic supply q...
Senegal                        Total Population - Both sexesDomestic supply q...
Seychelles                     ProductionImport QuantityStock VariationExport...
Sierra Leone                   Total Population - Both sexesDomestic supply q...
South Africa                   Total Population - Both sexesDomestic supply q...
Sudan                          Total Population - Both sexesDomestic supply q...
Sudan (former)                 Import QuantityDomestic supply quantityFeedOth...
Togo                           Total Population - Both sexesDomestic supply q...
Tunisia                        Total Population - Both sexesDomestic supply q...
Uganda                         Total Population - Both sexesDomestic supply q...
United Republic of Tanzania    Total Population - Both sexesDomestic supply q...
Zambia                         Total Population - Both sexesDomestic supply q...
Zimbabwe                       Total Population - Both sexesDomestic supply q...
Name: Element, dtype: object

In [23]:
#20 -- 49 countries
a.groupby('Area').describe()

                            Area Code                                          \
                                count   mean  std    min    25%    50%    75%
Area
Algeria                        1313.0    4.0  0.0    4.0    4.0    4.0    4.0
Angola                         1424.0    7.0  0.0    7.0    7.0    7.0    7.0
Benin                          1285.0   53.0  0.0   53.0   53.0   53.0   53.0
Botswana                       1378.0   20.0  0.0   20.0   20.0   20.0   20.0
Burkina Faso                   1409.0  233.0  0.0  233.0  233.0  233.0  233.0
Cabo Verde                     1260.0   35.0  0.0   35.0   35.0   35.0   35.0
Cameroon                       1460.0   32.0  0.0   32.0   32.0   32.0   32.0
Central African Republic       1344.0   37.0  0.0   37.0   37.0   37.0   37.0
Chad                           1343.0   39.0  0.0   39.0   39.0   39.0   39.0
Comoros                          45.0   45.0  0.0   45.0   45.0   45.0   45.0
Congo                          1413.0   46.0  0.0   46.0   46.0   46.0   46.0
Côte d'Ivoire                  1467.0  107.0  0.0  107.0  107.0  107.0  107.0
Djibouti                       1095.0   72.0  0.0   72.0   72.0   72.0   72.0
Egypt                          1488.0   59.0  0.0   59.0   59.0   59.0   59.0
Eswatini                       1284.0  209.0  0.0  209.0  209.0  209.0  209.0
Ethiopia                       1447.0  238.0  0.0  238.0  238.0  238.0  238.0
Ethiopia PDR                     39.0   62.0  0.0   62.0   62.0   62.0   62.0
Gabon                          1245.0   74.0  0.0   74.0   74.0   74.0   74.0
Gambia                         1168.0   75.0  0.0   75.0   75.0   75.0   75.0
Ghana                          1354.0   81.0  0.0   81.0   81.0   81.0   81.0
Guinea                         1410.0   90.0  0.0   90.0   90.0   90.0   90.0
Guinea-Bissau                  1128.0  175.0  0.0  175.0  175.0  175.0  175.0
Kenya                          1560.0  114.0  0.0  114.0  114.0  114.0  114.0
Lesotho                        1150.0  122.0  0.0  122.0  122.0  122.0  122.0
Liberia                        1206.0  123.0  0.0  123.0  123.0  123.0  123.0
Madagascar                     1439.0  129.0  0.0  129.0  129.0  129.0  129.0
Malawi                         1447.0  130.0  0.0  130.0  130.0  130.0  130.0
Mali                           1293.0  133.0  0.0  133.0  133.0  133.0  133.0
Mauritania                     1195.0  136.0  0.0  136.0  136.0  136.0  136.0
Mauritius                      1378.0  137.0  0.0  137.0  137.0  137.0  137.0
Morocco                        1393.0  143.0  0.0  143.0  143.0  143.0  143.0
Mozambique                     1427.0  144.0  0.0  144.0  144.0  144.0  144.0
Namibia                        1283.0  147.0  0.0  147.0  147.0  147.0  147.0
Niger                          1403.0  158.0  0.0  158.0  158.0  158.0  158.0
Nigeria                        1474.0  159.0  0.0  159.0  159.0  159.0  159.0
Rwanda                         1426.0  184.0  0.0  184.0  184.0  184.0  184.0
Sao Tome and Principe          1177.0  193.0  0.0  193.0  193.0  193.0  193.0
Senegal                        1462.0  195.0  0.0  195.0  195.0  195.0  195.0
Seychelles                       68.0  196.0  0.0  196.0  196.0  196.0  196.0
Sierra Leone                   1242.0  197.0  0.0  197.0  197.0  197.0  197.0
South Africa                   1399.0  202.0  0.0  202.0  202.0  202.0  202.0
Sudan                          1316.0  276.0  0.0  276.0  276.0  276.0  276.0
Sudan (former)                   53.0  206.0  0.0  206.0  206.0  206.0  206.0
Togo                           1294.0  217.0  0.0  217.0  217.0  217.0  217.0
Tunisia                        1338.0  222.0  0.0  222.0  222.0  222.0  222.0
Uganda                         1458.0  226.0  0.0  226.0  226.0  226.0  226.0
United Republic of Tanzania    1419.0  215.0  0.0  215.0  215.0  215.0  215.0
Zambia                         1451.0  251.0  0.0  251.0  251.0  251.0  251.0
Zimbabwe                       1393.0  181.0  0.0  181.0  181.0  181.0  181.0

                                   Item Code               ...    Y2017  \
                               max     count         mean  ...      75%
Area                                                       ...
Algeria                        4.0    1313.0  2690.063214  ...  28.0000
Angola                         7.0    1424.0  2682.519663  ...  14.0000
Benin                         53.0    1285.0  2687.698054  ...  13.0000
Botswana                      20.0    1378.0  2688.608128  ...   2.1600
Burkina Faso                 233.0    1409.0  2681.898510  ...   8.0000
Cabo Verde                    35.0    1260.0  2695.830159  ...   3.0000
Cameroon                      32.0    1460.0  2682.245205  ...  21.0000
Central African Republic      37.0    1344.0  2684.186012  ...   4.6800
Chad                          39.0    1343.0  2685.427401  ...   6.0000
Comoros                       45.0      45.0  2766.977778  ...   0.8000
Congo                         46.0    1413.0  2683.672328  ...   3.0000
Côte d'Ivoire                107.0    1467.0  2682.220859  ...  15.0000
Djibouti                      72.0    1095.0  2699.614612  ...   2.1700
Egypt                         59.0    1488.0  2685.864919  ...  47.0000
Eswatini                     209.0    1284.0  2691.724299  ...   3.4750
Ethiopia                     238.0    1447.0  2680.139599  ...  18.1075
Ethiopia PDR                  62.0      39.0  2765.461538  ...   0.0000
Gabon                         74.0    1245.0  2694.305221  ...   5.0000
Gambia                        75.0    1168.0  2692.981164  ...   3.0000
Ghana                         81.0    1354.0  2687.842688  ...  29.0000
Guinea                        90.0    1410.0  2682.372340  ...   8.0000
Guinea-Bissau                175.0    1128.0  2691.111702  ...   4.3325
Kenya                        114.0    1560.0  2683.100641  ...  17.0000
Lesotho                      122.0    1150.0  2695.085217  ...   3.1725
Liberia                      123.0    1206.0  2694.800166  ...   4.0000
Madagascar                   129.0    1439.0  2685.377345  ...   7.0000
Malawi                       130.0    1447.0  2680.987560  ...   8.0000
Mali                         133.0    1293.0  2683.585460  ...  21.5000
Mauritania                   136.0    1195.0  2696.323849  ...   5.5875
Mauritius                    137.0    1378.0  2693.459361  ...   3.6925
Morocco                      143.0    1393.0  2687.065327  ...  34.0000
Mozambique                   144.0    1427.0  2684.168886  ...  12.8625
Namibia                      147.0    1283.0  2691.134061  ...   5.7000
Niger                        158.0    1403.0  2682.635068  ...   4.0000
Nigeria                      159.0    1474.0  2682.738806  ...  61.0000
Rwanda                       184.0    1426.0  2681.686536  ...   5.0000
Sao Tome and Principe        193.0    1177.0  2691.631266  ...   1.0000
Senegal                      195.0    1462.0  2682.749658  ...   8.8875
Seychelles                   196.0      68.0  2768.617647  ...   0.4475
Sierra Leone                 197.0    1242.0  2691.872786  ...   6.0000
South Africa                 202.0    1399.0  2687.190136  ...  55.5000
Sudan                        276.0    1316.0  2685.912614  ...  19.3000
Sudan (former)               206.0      53.0  2766.622642  ...   0.0000
Togo                         217.0    1294.0  2688.429675  ...  10.0000
Tunisia                      222.0    1338.0  2692.689088  ...  19.0000
Uganda                       226.0    1458.0  2681.144719  ...  14.0000
United Republic of Tanzania  215.0    1419.0  2684.671600  ...  27.0000
Zambia                       251.0    1451.0  2682.840110  ...   6.0000
Zimbabwe                     181.0    1393.0  2684.344580  ...   8.0000

                                         Y2018                            \
                                   max   count         mean          std
Area
Algeria                       41389.00  1298.0   263.274253  1590.356861
Angola                        29817.00  1396.0   168.486160  1137.007472
Benin                         11175.00  1252.0    99.808866   545.635050
Botswana                       2341.00  1361.0    16.994181   113.793798
Burkina Faso                  19193.00  1373.0    82.280204   646.445752
Cabo Verde                     2530.00  1192.0    12.267282   107.229191
Cameroon                      24566.00  1432.0   162.725510   911.207104
Central African Republic       4596.00  1308.0    23.013433   166.536536
Chad                          15017.00  1305.0    55.388690   471.707604
Comoros                          16.65    45.0     1.329778     3.578664
Congo                          5111.00  1377.0    30.505105   201.177396
Côte d'Ivoire                 24437.00  1455.0   156.026117   975.517379
Djibouti                       2664.00  1040.0    22.806692   144.371308
Egypt                         96443.00  1468.0   580.826240  3540.908442
Eswatini                       5553.00  1231.0    44.715735   399.039402
Ethiopia                     106400.00  1425.0   316.343060  3200.112189
Ethiopia PDR                      0.00    39.0     0.000000     0.000000
Gabon                          2640.00  1192.0    23.774648   133.556364
Gambia                         2544.00  1118.0    21.032021   149.112662
Ghana                         29121.00  1337.0   268.448497  1818.707255
Guinea                        12068.00  1385.0    74.557458   457.409055
Guinea-Bissau                  2233.00  1091.0    17.413309   121.702160
Kenya                         50221.00  1548.0   175.010853  1448.717847
Lesotho                        2475.00  1094.0    17.467303   130.133018
Liberia                        4702.00  1133.0    26.151659   185.772512
Madagascar                    25571.00  1424.0    94.505927   812.119103
Malawi                        17670.00  1410.0   132.883752   834.095024
Mali                          18512.00  1260.0   126.211444   764.364610
Mauritania                    51864.00  1170.0   134.598248  1963.648701
Mauritius                      3713.00  1342.0    35.134806   260.042960
Morocco                       38348.00  1368.0   291.864963  1924.375988
Mozambique                    28649.00  1400.0   117.810036   992.481626
Namibia                        2465.00  1256.0    23.367866   134.470712
Niger                         21602.00  1368.0    97.940687   739.976796
Nigeria                      190873.00  1456.0  1030.064725  7844.078817
Rwanda                        11981.00  1403.0    53.342181   405.123587
Sao Tome and Principe          2407.00  1109.0    11.547782   108.391990
Senegal                       15419.00  1448.0    65.948771   494.072802
Seychelles                      204.02    68.0     6.505000    30.566295
Sierra Leone                   7488.00  1197.0    46.768363   309.591137
South Africa                  57010.00  1396.0   365.177629  2217.539021
Sudan                         40813.00  1268.0   211.399361  1391.731877
Sudan (former)                    0.00    53.0     0.000000     0.000000
Togo                           7698.00  1266.0    43.342812   281.434529
Tunisia                       11433.00  1320.0    96.472098   486.351462
Uganda                        41167.00  1445.0   153.735121  1249.223877
United Republic of Tanzania   54660.00  1408.0   248.411513  1773.352142
Zambia                        16854.00  1421.0    71.501949   584.960419
Zimbabwe                      14237.00  1356.0    56.475966   479.406351


                                min  25%    50%      75%        max
Area
Algeria                       -90.0  0.0  1.000  27.2850   42228.00
Angola                       -240.0  0.0  0.030  12.0000   30810.00
Benin                        -256.0  0.0  0.590  13.2500   11485.00
Botswana                      -35.0  0.0  0.000   3.0000    2342.00
Burkina Faso                  -77.0  0.0  0.010   8.2000   19751.00
Cabo Verde                    -16.0  0.0  0.010   3.0000    2541.00
Cameroon                     -175.0  0.0  0.310  21.0000   25216.00
Central African Republic       -4.0  0.0  0.000   3.5500    4666.00
Chad                          -10.0  0.0  0.000   6.0000   15478.00
Comoros                         0.0  0.0  0.020   0.8000      16.65
Congo                         -17.0  0.0  0.000   3.0000    5244.00
Côte d'Ivoire                -151.0  0.0  0.370  14.9450   25069.00
Djibouti                      -10.0  0.0  0.020   2.7300    2694.00
Egypt                       -3396.0  0.0  1.000  48.0000   98424.00
Eswatini                      -10.0  0.0  0.050   4.0000    5596.00
Ethiopia                    -1000.0  0.0  0.140  20.0000  109224.00
Ethiopia PDR                    0.0  0.0  0.000   0.0000       0.00
Gabon                         -22.0  0.0  0.010   5.0000    2633.00
Gambia                         -4.0  0.0  0.010   3.0000    2533.00
Ghana                        -502.0  0.0  1.000  28.0000   30317.00
Guinea                        -12.0  0.0  0.000   9.0000   12414.00
Guinea-Bissau                  -3.0  0.0  0.050   4.0000    2229.00
Kenya                        -177.0  0.0  0.640  16.0000   51393.00
Lesotho                       -70.0  0.0  0.010   3.0000    2323.00
Liberia                       -23.0  0.0  0.020   3.7200    4819.00
Madagascar                   -336.0  0.0  0.030   7.3000   26262.00
Malawi                       -237.0  0.0  0.000   7.0000   18143.00
Mali                         -598.0  0.0  0.900  18.4900   19078.00
Mauritania                    -12.0  0.0  0.010   5.8650   51864.00
Mauritius                     -34.0  0.0  0.120   4.0000    3155.00
Morocco                      -169.0  0.0  2.000  36.0000   38349.00
Mozambique                  -1445.0  0.0  0.230  11.0000   29496.00
Namibia                       -30.0  0.0  0.110   5.0000    2469.00
Niger                        -434.0  0.0  0.000   4.0000   22443.00
Nigeria                      -374.0  0.0  0.570  54.5950  195875.00
Rwanda                       -682.0  0.0  0.000   4.0000   12302.00
Sao Tome and Principe          -1.0  0.0  0.000   1.0000    2446.00
Senegal                      -101.0  0.0  0.060   8.0075   15854.00
Seychelles                      0.0  0.0  0.035   0.4475     204.02
Sierra Leone                 -180.0  0.0  0.080   6.0000    7650.00
South Africa                 -597.0  0.0  3.000  50.5000   57793.00
Sudan                         -99.0  0.0  0.060  20.0000   41802.00
Sudan (former)                  0.0  0.0  0.000   0.0000       0.00
Togo                          -84.0  0.0  0.260   9.0000    7889.00
Tunisia                      -319.0  0.0  1.320  18.0000   11565.00
Uganda                       -271.0  0.0  0.020  12.7300   42729.00
United Republic of Tanzania  -913.0  0.0  1.000  28.2500   56313.00
Zambia                       -529.0  0.0  0.000   6.0000   17352.00
Zimbabwe                     -273.0  0.0  0.120   7.0000   14439.00

[49 rows x 64 columns]